nynjaetc/analytics/urls.py
from django.conf.urls import patterns, url
urlpatterns = patterns(
    '',
    url(r'^$',
        'nynjaetc.analytics.views.analytics_table',
        name="analytics_table"),

    url(r'^testing/$',
        'nynjaetc.analytics.views.analytics_table_testing',
        name="analytics_table_testing"),

    url(r'csv/$',
        'nynjaetc.analytics.views.analytics_csv',
        name="analytics_csv")
)

nynjaetc/treatment_activity/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^$',
        'nynjaetc.treatment_activity.views.choose_treatment_path',
        name='choose-treatment-path'),

    url(r'^(?P<path_id>\d+)/(?P<node_id>\d+)/$',
        'nynjaetc.treatment_activity.views.get_next_steps',
        name="get-next-steps")
)

nynjaetc/urls.py
import os.path

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import password_change, password_change_done, \
    password_reset, password_reset_done, password_reset_complete, \
    password_reset_confirm
from django.views.generic import TemplateView
from registration.backends.default.views import ActivationView

import nynjaetc.main.regviews as regviews
import nynjaetc.main.views as views


admin.autodiscover()

site_media_root = os.path.join(os.path.dirname(__file__), "../media")

redirect_after_logout = getattr(settings, 'LOGOUT_REDIRECT_URL', None)
auth_urls = (r'^accounts/', include('django.contrib.auth.urls'))
logout_page = (
    r'^accounts/logout/$',
    'django.contrib.auth.views.logout',
    {'next_page': redirect_after_logout})
if hasattr(settings, 'CAS_BASE'):
    auth_urls = (r'^accounts/', include('djangowind.urls'))
    logout_page = (
        r'^accounts/logout/$',
        'djangowind.views.logout',
        {'next_page': redirect_after_logout})

urlpatterns = patterns(
    '',
    auth_urls,
    logout_page,
    url(r'^_impersonate/', include('impersonate.urls')),
    (r'^_pagetree/', include('pagetree.urls')),
    (r'^_quiz/', include('quizblock.urls')),
    (r'^_rgt/', include('nynjaetc.treatment_activity.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^analytics/', include('nynjaetc.analytics.urls')),

    ('^about/$', 'nynjaetc.main.views.background',
     {'content_to_show': 'about'}),
    ('^help/$', 'nynjaetc.main.views.background',
     {'content_to_show': 'help'}),
    ('^contact/$', 'nynjaetc.main.views.background',
     {'content_to_show': 'contact'}),
    ('^credits/$', 'nynjaetc.main.views.background',
     {'content_to_show': 'credits'}),

    # override the default urls for password
    url(r'^password/change/$',
        password_change,
        name='password_change'),
    url(r'^password/change/done/$',
        password_change_done,
        name='password_change_done'),
    url(r'^password/reset/$',
        password_reset,
        name='password_reset'),
    url(r'^password/reset/done/$',
        password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/complete/$',
        password_reset_complete,
        name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        name='password_reset_confirm'),

    # have to pull in a bunch of registration's urls
    # so we can override one. :(
    url(r'^accounts/activate/complete/$',
        TemplateView.as_view(
            template_name='registration/activation_complete.html'),
        name='registration_activation_complete'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(),
        name='registration_activate'),
    url(r'^accounts/register/complete/$',
        TemplateView.as_view(
            template_name='registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^accounts/register/closed/$',
        TemplateView.as_view(
            template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
    (r'^accounts/', include('registration.auth_urls')),
    url(r'^accounts/register/$', regviews.RegistrationView.as_view(),
        name='registration_register'),

    (r'^resend_activation_email/$', views.ResendActivationEmailView.as_view()),

    (r'manage/$', TemplateView.as_view(template_name='main/manage.html')),
    (r'manage/altnav/$', views.AltNavListView.as_view()),
    (r'manage/altnav/add/$', views.CreateAltNavView.as_view()),
    (r'manage/altnav/(?P<pk>\d+)/delete/$', views.DeleteAltNavView.as_view()),

    (r'manage/secpref/$', views.SecPrefListView.as_view()),
    (r'manage/secpref/add/$', views.CreateSecPrefView.as_view()),
    (r'manage/secpref/(?P<pk>\d+)/delete/$',
     views.DeleteSecPrefView.as_view()),

    (r'^stats/$', TemplateView.as_view(template_name="stats.html")),
    (r'smoketest/', include('smoketest.urls')),
    (r'^uploads/(?P<path>.*)$',
     'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    # these need to be last
    (r'^edit/(?P<path>.*)$', views.EditView.as_view(),
     {}, 'edit-page'),
    (r'^latest/(?P<path>.*)$', views.LatestPageView.as_view(),
     {}, 'latest-page'),
    (r'^record_section_as_answered_correctly/$',
     views.RecordSectionAsAnsweredCorrectlyView.as_view(),
     {}, 'record_section_as_answered_correctly'),
    (r'^(?P<path>.*)$', views.PageView.as_view()),
)

nynjaetc/main/models.py
from django.db import models
from pagetree.models import Section
from django.contrib.auth.models import User
from datetime import datetime
from django.utils.timezone import utc
from django.db.models import signals
from django_fields.fields import EncryptedEmailField, EncryptedCharField
from quizblock.models import Quiz
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.forms import PasswordResetForm
from registration.forms import RegistrationForm
from django.core.exceptions import ImproperlyConfigured
from django.utils.encoding import DjangoUnicodeDecodeError
from django import forms
from django.conf import settings


def is_leaf_or_has_content(self):
    is_leaf = (len(self.get_children()) == 0)
    has_content = (self.pageblock_set.count())
    return is_leaf or has_content  # Get it?
Section.is_leaf_or_has_content = is_leaf_or_has_content


def next_with_content(self):
    s = self.get_next()
    while s is not None:
        if s.is_leaf_or_has_content():
            return s
        s = s.get_next()
    return None
Section.next_with_content = next_with_content


def prev_with_content(self):
    s = self.get_previous()
    while s is not None:
        if s.is_leaf_or_has_content():
            return s
        s = s.get_previous()
    return None
Section.prev_with_content = prev_with_content


class UserProfile(models.Model):

    class Meta:
        app_label = 'main'

    def __unicode__(self):
        return "Encrypted email and HRSA ID for user %d" % self.user.id
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    encrypted_email = EncryptedEmailField()
    hrsa_id = EncryptedCharField()

    @staticmethod
    def find_user_profiles_by_plaintext_email(plaintext_email):
        """ this isn't scaleable but should be fine in the short term."""
        try:
            return [x for x in UserProfile.objects.all()
                    if x.encrypted_email == plaintext_email]
        except DjangoUnicodeDecodeError:
            raise ImproperlyConfigured(
                """Looks like the setting for encryption /decryption
                doesn't match one of the values in the database.""")


class SectionTimestamp(models.Model):
    """Marks when this section was last visited by a particular user."""
    def __unicode__(self):
        return self.section.get_path()

    section = models.ForeignKey(Section, null=False, blank=False)
    timestamp = models.DateTimeField(null=False)
    user = models.ForeignKey(User, blank=False, null=False)
    unique_together = ("user", "section")

    def set_to_now(self):
        the_now = datetime.utcnow().replace(tzinfo=utc)
        self.timestamp = the_now
        self.save()


class SectionAlternateNavigation(models.Model):
    """Allows extra back and next buttons on certain special sections."""

    class Meta:
        verbose_name = 'Alt. nav setting'
        verbose_name_plural = 'Alt. nav settings'

    def __unicode__(self):
        return "Alternate nav for %s" % self.section.get_path()

    section = models.ForeignKey(Section, null=False, blank=False, unique=True)

    alternate_back = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text=("An alternate back button on this section "
                   "will point to this path."))

    alternate_back_label = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text="A label for this alternate back button, if necessary.")

    alternate_next = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text=("An alternate next button on this section will point "
                   "to this path."))

    alternate_next_label = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text="A label for this alternate next button, if necessary.")


class SectionQuizAnsweredCorrectly(models.Model):

    """Marks, for nav purposes, when a section has been correctly answered."""
    def __unicode__(self):
        return self.section.get_path()
    section = models.ForeignKey(Section, null=False, blank=False)
    user = models.ForeignKey(User, blank=False, null=False)
    unique_together = ("user", "section")


class Preference(models.Model):

    def __unicode__(self):
        return self.slug
    """ A way in which a Section can be special.
    Examples: Sections whose back buttons should be hidden.
    Sections whose next buttons should be hidden.
    Sections whose nav entry might be special in some way.
    """
    slug = models.SlugField(unique=True, null=False, blank=False)

    def sections(self):
        return [s.section for s in self.sectionpreference_set.all()]


class SectionPreference(models.Model):

    def __unicode__(self):
        return "%s has %s" % (self.section, self.preference)
    """ A way to mark a section as special in some way."""
    section = models.ForeignKey(Section, null=False, blank=False)
    preference = models.ForeignKey(Preference, null=False, blank=False)

    class Meta:
        ordering = ['section', 'preference']
        unique_together = ("section", "preference")


def my_email_user(self, subject, message, from_email=None):
    """
    Sends an email to this user's encrypted email, if there is one.
    """
    self.email = self.userprofile.encrypted_email
    self.original_email_user(subject, message, from_email)
    self.email = '*****'  # note -- this isn't stored.


def store_encrypted_email(user):
    """
    Saves the email to the profile.
    Then replaces it with an arbitrary value.
    Note -- since this triggers a second save,
    don't call it from signals.post_save.connect
    on an updated object.
    We're NOT allowing people to change their
    email, but they CAN
    reset their passwords at:
        /accounts/password_change/
    """

    if user is None or user.email is None:
        raise ValueError('User or email is None.')
    the_profile, created = UserProfile.objects.get_or_create(user=user)
    the_profile.encrypted_email = user.email
    the_profile.save()
    # save dummy value in regular user field:
    user.email = '*****'
    user.save()


def steal_email(sender, instance, **kwargs):
    if kwargs['created']:
        store_encrypted_email(instance)


# MONKEY-PATCHERY

User.original_email_user = User.email_user
User.email_user = my_email_user
signals.post_save.connect(steal_email, sender=User)


Quiz.original_submit = Quiz.submit


def my_quiz_submit(self, user, data):
    hrsa_question_key = settings.HRSA_ID_FIELD

    hrsa_id = data.get(hrsa_question_key, None)

    if hrsa_id is not None:
        hrsa_id = data[hrsa_question_key]
        the_profile, created = UserProfile.objects.get_or_create(user=user)
        the_profile.hrsa_id = hrsa_id
        the_profile.save()
        data[hrsa_question_key] = "*****"
    self.original_submit(user, data)
Quiz.submit = my_quiz_submit


PasswordResetForm.original_save = PasswordResetForm.save


def my_password_reset_form_save(
        self, domain_override=None,
        subject_template_name='registration/password_reset_subject.txt',
        email_template_name='registration/password_reset_email.html',
        html_email_template_name=None,
        use_https=False, token_generator=default_token_generator,
        from_email=None, request=None):

    # unencrypt emails
    for user in self.users_cache:
        user.email = user.userprofile.encrypted_email
        user.save()

    # send emails
    self.original_save(domain_override,
                       subject_template_name,
                       email_template_name,
                       use_https, token_generator,
                       from_email, request)

    # re-encrypt emails
    for user in self.users_cache:
        user.email = "*****"
        user.save()
PasswordResetForm.save = my_password_reset_form_save


def my_password_reset_form_clean_email(self):
    plaintext_email = self.cleaned_data["email"]
    user_profiles = UserProfile.find_user_profiles_by_plaintext_email(
        plaintext_email)
    self.users_cache = [u.user for u in user_profiles if u.user.is_active]
    if not len(self.users_cache):
        msg = 'No user found matching the email address %s' % plaintext_email
        raise forms.ValidationError(msg)
    if any(not user.has_usable_password()
            for user in self.users_cache):
        msg = 'This user\'s password cannot be changed'
        raise forms.ValidationError(msg)
    return plaintext_email
PasswordResetForm.clean_email = my_password_reset_form_clean_email

RegistrationForm.original_clean = RegistrationForm.clean


def my_clean(self):
    self.original_clean()
    my_email = self.cleaned_data.get('email', None)
    if my_email:
        if UserProfile.find_user_profiles_by_plaintext_email(my_email):
            raise forms.ValidationError(
                """That email address is already taken.
                You can reset your password
                at the link below.""")
    return self.cleaned_data

RegistrationForm.clean = my_clean


def my_clean_username(self):
    existing = User.objects.filter(
        username__iexact=self.cleaned_data['username'])
    if existing.exists():
        raise forms.ValidationError(
            """That username is already taken.
            You can reset your password at the link below.""")
    else:
        return self.cleaned_data['username']

RegistrationForm.clean_username = my_clean_username


RegistrationForm.base_fields['username'].label = 'Please choose a username:'
RegistrationForm.base_fields['email'].label = (
    """Please give us a current email address. """
    """This address will be used to confirm your account. """
    """We may also send a follow-up survey to this address to """
    """ask about your experience with our online learning content. """
    """We will never sell your email address or use it """
    """for any other reason.""")

nynjaetc/treatment_activity/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from nynjaetc.treatment_activity.models import TreatmentPath, TreatmentNode
from json import loads, dumps


@login_required
def get_next_steps(request, path_id, node_id):
    if not request.is_ajax():
        return HttpResponseForbidden()

    node = TreatmentNode.objects.get(id=node_id)

    prev, node, next_steps = get_to_decision_point(
        node, request.POST.get('steps'))
    data = {'steps': next_steps,
            'path': path_id,
            'can_edit': request.user.is_superuser}
    if prev:
        data['node'] = prev.id

    return HttpResponse(dumps(data, indent=2),
                        content_type="application/json")


def get_to_decision_point(node, steps_json):
    next_steps = []
    prev = None
    if node.is_decisionpoint():
        steps = loads(steps_json)
        decision = steps[len(steps) - 1]['decision']
        node = node.child_from_decision(decision)

        next_steps.append(node.to_json())
        prev = node

    for node in node.get_descendants():
        if prev and prev.is_decisionpoint():
            break
        else:
            next_steps.append(node.to_json())
            prev = node
    return prev, node, next_steps


@login_required
def choose_treatment_path(request):
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseForbidden()

    params = loads(request.POST.get('state'))
    cirrhosis = params.get('cirrhosis', None)
    status = params.get('status', None)
    drug = params.get('drug', None)

    data = {}

    if cirrhosis is None or status is None or drug is None:
        data = {"error": "Missing required parameters"}

        return HttpResponse(dumps(data, indent=2),
                            content_type="application/json")
    try:
        path = TreatmentPath.objects.get(cirrhosis=cirrhosis,
                                         treatment_status=status,
                                         drug_choice=drug)

        return get_next_steps(request, path.id, path.tree.id)

    except TreatmentPath.DoesNotExist:
        msg = "Can't find a path. [cirrhosis: %s, status: %s, drug: %s]" \
            % (cirrhosis, status, drug)
        data = {"error": msg}

        return HttpResponse(dumps(data, indent=2),
                            content_type="application/json")

nynjaetc/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
<div class="hero-unit">
<h1>It works</h1>
<p>Congratulations! Now start coding.</p>
</div>
{% endblock %}

nynjaetc/templates/main/instructor_page.html
{% extends "base.html" %}

{% block title %}{{section.label}} (instructor){% endblock %}
{% block sidenav %}
	<!-- ###### Secondary Navigation ###### -->
	<div id="secondary_navigation">
		<div id="fadetop"></div>
		<div class="block">
			<h3>Sections</h3>
{% with "/instructor" as menu_base %}
{% include "main/menu.html" %}
{% endwith %}
		</div><!-- div id="block" -->
		<div id="fadebottom"></div>
	</div><!-- div id="secondary_navigation" -->
{% endblock %}


{% block content %}
<a href="{{section.get_absolute_url}}">student view of page</a>
<h1>{{ section.label }}</h1>

{% if quizzes %}
{% for quiz in quizzes %}
<h3>quiz {{quiz.id}}</h3>

{% if quiz.submission_set.count %}
<table width="100%">
{% for submission in quiz.submission_set.all %}
<tr class="submissionheader">
<th>{{submission.user.first_name}} {{submission.user.last_name}} ({{submission.user.username}})</th>
<td>{{submission.submitted}}</td>
</tr>
{% for response in submission.response_set.all %}
<tr class="submissionresponse">
<td>Question {{response.question.ordinality}}: {{response.question.text}}</td>
<td class="{% if response.question.answerable %}{% if response.is_correct %}correct{% else %}incorrect{% endif %}{% endif %}">{{response.value}}</td>
</tr>
{% endfor %}
{% endfor %}
</table>
{% else %}
<p>no submissions</p>
{% endif %}

{% endfor %}
{% else %}
<p>no quizzes on this page</p>
{% endif %}

<br style="clear:both"/>
{% endblock %}

{% block content-nav %}

{% if section.get_previous %}
<a href="/instructor{{section.get_previous.get_absolute_url}}" id="previous">« {{section.get_previous.label}}</a>
{% endif %}

{% if section.get_next %}
<a href="/instructor{{section.get_next.get_absolute_url}}" id="next">{{section.get_next.label}} »</a>
{% endif %}

{% endblock %}

nynjaetc/templates/main/manage.html
{% extends 'base.html' %}

{% block content %}

<ul class="breadcrumb">
  <li class="active">manage</li>
</ul>


<ul>
	<li><a href="altnav/">Alternate Navigation Settings</a></li>
	<li><a href="secpref/">Section Preferences</a></li>
</ul>

{% endblock %}

nynjaetc/templates/main/menu.html
<ul>
{% for s in module.get_descendants %}
{% ifequal s.id module.id %}
{% else %}
<li class="menu-{{s.depth}} {% ifequal s.id section.id %}the_current_section{%else %}not_the_current_section{%endifequal%}">
  {% ifequal s.id section.id %}
        <span class="the_current_section">{{s.label}}</span>
  {%else %}
    <a href="{{menu_base}}{{s.get_absolute_url}}">{{s.label}}</a>
  {% endifequal %}
 {% if s.get_children %}
 <ul id="section-ul-{{s.id}}">
 {% else %}
 {% if s.is_last_child %}
 {% for lc in s.closing_children %}
      </ul>
 {% endfor %}
{% endif %}
{% endif %}
{% if s.get_children %}
{% else %}
    </li>
{% endif%}
{% endifequal %}
{% endfor %}
</ul>

nynjaetc/templates/main/page.html
{% extends 'base.html' %}
{% load render %}
{% block js %}
<script type="text/javascript" src="{{STATIC_URL}}js/chapter_marker_player.js"></script>
{% for block in section.pageblock_set.all %}
{% renderjs block %}
{% endfor %}
{% endblock %}

{% block css %}
{% for block in section.pageblock_set.all %}
{% rendercss block %}
{% endfor %}
{% endblock %}

{% block module_slug %}{{module.slug}}{% endblock %}

{% block title %}{{section.label}}{% endblock %}

{% block pagetitle %}<h2 class="pagetitle">{{section.label}}</h2>{% endblock %}

{% block sidenav %}
    {% if whether_to_show_nav %}
        <!-- ###### Secondary Navigation ###### -->
        {% if module.get_children %}
        {% include "main/menu.html" %}
        {% endif %}    
    {% endif %}
{% endblock %}


{% block primarynavtabs %}
    {% if whether_to_show_nav %}
    {% for section in module_info %}
        <li{% ifequal section.id module.id %} class="active"{% endifequal %}><a href="{{section.url}}">{{section.label}}</a></li>
        {% endfor %}
    {%endif %}
{% endblock %}

{% block navrightextra %}
    <ul class="nav">
        {% if user.is_staff %}
        <li><a href="/edit{{section.get_absolute_url}}">edit page</a></li>
        {% endif %}
    </ul>
{% endblock %}



{% block breadcrumbs %}
  <ul>
       {% for breadcrumb in path %}
                <li><a href ="{{breadcrumb.get_absolute_url}}">{{breadcrumb}}</a><span class="divider">/</span></li>
       {% endfor %}        
            
  </ul>
{% endblock breadcrumbs %}



{% block content %}
<div id="content" class ="module-{{module.slug}}">

{% if needs_submit %}
{% if is_submitted %}
{% else %}
<form action="." method="post">
{% endif %}
{% endif %}


{% for block in section.pageblock_set.all %}
<div class="pageblock{% if block.css_extra %} {{block.css_extra}}{% endif %}">
{% if block.label %}<h4>{{block.label}}</h4>{% endif %}
{% render block %}
</div>
{% endfor %}


{% if needs_submit %}
{% if request.user.is_anonymous %}
{% else %}

{% if is_submitted %}
<form action="." method="post">
<input type="hidden" name="action" value="reset" />
    {%comment %}
        <input type="submit" value="clear your answers and try again" class="btn" />
    {%endcomment %}
</form>
{% else %}
<input type="submit" value="Submit" class="btn btn-primary" />

</form>
{% endif %}
{% endif %}
{% endif %}
</div>
{% endblock %}

{% block content-nav %}
    <ul class="pager main">
    {% if not section_preferences.hide_previous_button %}
        {% if section.prev_with_content %}
         <li class="previous">
		        <a href="{{section.prev_with_content.get_absolute_url}}">&larr; {{section.prev_with_content.label}}  </a>
          </li>
        {% endif %}
    {% endif %}
    {%comment %}These alternate nav buttons are editable in /admin/main/sectionalternatenavigation/ {%endcomment %}
    {% with alternate_nav=section.sectionalternatenavigation_set.get %}
        {% if alternate_nav.alternate_back %}
             <!-- Alternate back button -->
             <li class="previous">
	            <a href="{{alternate_nav.alternate_back}}">&larr; {{alternate_nav.alternate_back_label}}</a>
          </li>
        {%endif %}
    {%endwith %}
    
    
    
    
    {%comment %}These alternate nav buttons are editable in /admin/main/sectionalternatenavigation/ {%endcomment %}
    {% with alternate_nav=section.sectionalternatenavigation_set.get %}
        {% if alternate_nav.alternate_next %}
             <!-- Alternate "next" button -->
             <li class="next">
	            <a href="{{alternate_nav.alternate_next}}">{{alternate_nav.alternate_next_label}} &rarr;</a>
            </li>
        {%endif %}
    {%endwith %}
    {% if not section_preferences.hide_next_button %}
        {% if section.next_with_content %}
        {% with section.next_with_content as next_section %}
        <li class="next"><a href="{{section.next_with_content.get_absolute_url}}">{{section.next_with_content.label}}&rarr;</a></li>
        {% endwith %}
        {% endif %}
        
    {% endif %}
    </ul>

    <p class ="debug_info">Section is <strong>{{section}}</strong></p>
    <p class ="debug_info">Path is  <strong>{{path}}</strong></p>
    <p class ="debug_info">Module is <strong>{{module}}</strong></p>
    <p class ="debug_info">Top level is:  <strong>{{path.0}}</strong></p>
    <p class ="debug_info">Middle level is:  <strong>{{path.1}}</strong></p>
    <p class ="debug_info">Bottom level is:  <strong>{{path.2}}</strong></p>
    <p class ="debug_info">Depth is  <strong>{{depth}}</strong></p>
    <p class ="debug_info">in_quiz_sequence is  <strong>{{in_quiz_sequence}}</strong></p>
    <p class ="debug_info">already_visited is  <strong>{{already_visited}}</strong></p>
    <p class ="debug_info">already_answered is  <strong>{{already_answered}}</strong></p>
{% endblock %}

nynjaetc/templates/main/sectionalternatenavigation_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="/manage/">manage</a></li>
  <li><a href="/manage/altnav/">alt navs</a></li>
	<li class="active">add</li>
</ul>




<form action="." method="post">

<select name="section">
	<option value="">--------</option>
	{% for section in all_sections %}
	<option value="{{section.id}}">{{section.get_absolute_url}}</option>
	{% endfor %}
</select>

<div class="control-group">
    
        <label class="control-label" for="id_alternate_back">Alternate back</label>

        <div class="controls">
            <input id="id_alternate_back" maxlength="64" name="alternate_back" type="text" />

            

            
            <p class="help-block">
                An alternate back button on this section will point to this path.
            </p>
            

        </div>
    
</div>


    
<div class="control-group">
    
        <label class="control-label" for="id_alternate_back_label">Alternate back label</label>

        <div class="controls">
            <input id="id_alternate_back_label" maxlength="64" name="alternate_back_label" type="text" />

            

            
            <p class="help-block">
                A label for this alternate back button, if necessary.
            </p>
            

        </div>
    
</div>


    
<div class="control-group">
    
        <label class="control-label" for="id_alternate_next">Alternate next</label>

        <div class="controls">
            <input id="id_alternate_next" maxlength="64" name="alternate_next" type="text" />

            

            
            <p class="help-block">
                An alternate next button on this section will point to this path.
            </p>
            

        </div>
    
</div>


    
<div class="control-group">
    
        <label class="control-label" for="id_alternate_next_label">Alternate next label</label>

        <div class="controls">
            <input id="id_alternate_next_label" maxlength="64" name="alternate_next_label" type="text" />

            

            
            <p class="help-block">
                A label for this alternate next button, if necessary.
            </p>
            

        </div>
    
</div>

<input type="submit" value="add" class="btn btn-primary"/>
</form>

{% endblock %}

nynjaetc/templates/main/sectionpreference_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}

<ul class="breadcrumb">
  <li><a href="/manage/">manage</a></li>
  <li><a href="/manage/secpref/">section preferences</a></li>
	<li class="active">add</li>
</ul>


<form action="." method="post">


<div class="control-group">
    
        <label class="control-label" for="id_section">Section</label>

        <div class="controls">

            
<select name="section">
	<option value="">--------</option>
	{% for section in all_sections %}
	<option value="{{section.id}}">{{section.get_absolute_url}}</option>
	{% endfor %}
</select>

            

        </div>
    
</div>


    
<div class="control-group">
    
        <label class="control-label" for="id_preference">Preference</label>

        <div class="controls">

{{form.preference}}

        </div>
    
</div>


<input type="submit" class="btn btn-primary" value="add"/>
</form>
{% endblock %}